// Beach data for "Find Your Beach" quiz
const beaches = [
    // HIDDEN GEMS
    {
        name: "Lagoinha do Leste",
        nickname: "The Island's Crown Jewel",
        emoji: "🥾",
        type: "Pristine Wilderness",
        region: "South",
        description: "Earned through jungle trails and coastal paths, this pristine crescent rewards the adventurous. A stunning freshwater lagoon meets the sea, creating a geological phenomenon. Wild camping is permitted, with fresh water available from a stream.",
        waves: 5, crowds: 1, infrastructure: 0,
        water: "Crystal clear, cold Atlantic",
        bestFor: "Adventurers, hikers, photographers",
        notIdealFor: "Children, elderly, those wanting facilities",
        parking: "Pântano do Sul (~R$30) or Armação",
        food: "BRING EVERYTHING — zero commerce",
        bestTime: "Leave by 7-8am for full day",
        bestSeason: "March-April or Sept-Nov",
        proTip: "Hike in from Matadeiro when fresh, return via Pântano do Sul, then reward yourself at Bar do Arante restaurant.",
        access: "1-3 hour hike only (or boat ~R$50-80)",
        tags: ["pristine", "hiking", "adventure", "photography", "camping"],
        personality: "Hidden Cove Seeker",
        vibe: "hidden", effort: "hike", priority: "nature", practical: "surprise"
    },
    {
        name: "Praia do Saquinho",
        nickname: "Off-Grid Paradise",
        emoji: "🏝️",
        type: "Untouched Solitude",
        region: "South",
        description: "Among the emptiest beaches on the island, this off-grid paradise has no electricity and only ~20 families live here. The turquoise waters and complete isolation make it worth every step of the journey.",
        waves: 3, crowds: 1, infrastructure: 0.5,
        water: "Crystal clear, turquoise",
        bestFor: "Solitude seekers, photographers",
        notIdealFor: "Those wanting any conveniences",
        parking: "End of road at Solidão (~R$20-30)",
        food: "Bar do Quirino serves fresh fish—bring cash",
        bestTime: "Full day excursion, arrive early",
        bestSeason: "Summer for swimming",
        proTip: "The cement trail can be extremely slippery when wet due to moss—proper footwear essential. No cell signal in most areas.",
        access: "30-45 min hike from Solidão",
        tags: ["solitude", "pristine", "off-grid", "photography"],
        personality: "Solitude Seeker",
        vibe: "hidden", effort: "hike", priority: "nature", practical: "surprise"
    },
    {
        name: "Praia dos Naufragados",
        nickname: "Shipwreck Beach",
        emoji: "⚓",
        type: "Historic Adventure",
        region: "South",
        description: "Named for the 1753 shipwreck that killed 180+ Azorean settlers. The 1861 lighthouse delivers stunning panoramic views, and WWII-era cannons at Forte Marechal Moura add to the history. A freshwater river crosses the beach.",
        waves: 4, crowds: 1.5, infrastructure: 1,
        water: "Powerful waves, clear, cold",
        bestFor: "History buffs, adventurers",
        notIdealFor: "Non-swimmers, those wanting luxury",
        parking: "Caieira da Barra do Sul (~R$20)",
        food: "Basic seafood restaurants on beach",
        bestTime: "Morning departure, check tide for lighthouse",
        bestSeason: "Year-round (avoid muddy trail after heavy rain)",
        proTip: "Return options include asking fishermen for boat rides (~R$20-30). Check tide schedules for lighthouse access.",
        access: "50 min hike (~3km) or boat",
        tags: ["history", "adventure", "lighthouse", "hiking"],
        personality: "History Explorer",
        vibe: "hidden", effort: "hike", priority: "nature", practical: "surprise"
    },
    {
        name: "Praia do Gravatá",
        nickname: "The Secret Cove",
        emoji: "💎",
        type: "Intimate Escape",
        region: "East",
        description: "Unknown even to most locals, this 60-80 meter intimate cove transforms into a 'big blue pool' when swells come from the East or South. Only 2 fishermen's shacks exist here. The Pedra do Urubu viewpoint offers 360° panoramas.",
        waves: 3, crowds: 1, infrastructure: 0,
        water: "Cold, crystal clear, highly saline",
        bestFor: "Couples, photographers, solitude seekers",
        notIdealFor: "Those needing any facilities",
        parking: "Praia Mole lots (R$30-50 summer)",
        food: "Bring everything",
        bestTime: "Golden hour for photography",
        bestSeason: "E/S swells create calm lagoon conditions",
        proTip: "Trail begins at the paragliding ramp (Rampa Praia Mole). At the fork, go LEFT (right leads to private property with dogs).",
        access: "30 min trail from Praia Mole",
        tags: ["secret", "romantic", "photography", "intimate"],
        personality: "Secret Spot Finder",
        vibe: "hidden", effort: "walk", priority: "nature", practical: "surprise"
    },
    {
        name: "Costa da Lagoa",
        nickname: "Boat-Access Paradise",
        emoji: "⛵",
        type: "Culinary Adventure",
        region: "Lagoon",
        description: "Accessible only by 40-minute boat ride or 3-hour trail, this hidden gem features multiple beaches, a crystal pool waterfall, and 15+ restaurants serving authentic seafood including the famous carapeva fish found only in this lagoon.",
        waves: 1, crowds: 2, infrastructure: 3,
        water: "Calm lagoon",
        bestFor: "Day trips, gastronomy, couples, adventurous families",
        notIdealFor: "Late visitors (boats stop 6pm)",
        parking: "Free at Terminal Lacustre",
        food: "EXCELLENT — Restaurante Cachoeira, Lagoa Azul",
        bestTime: "Leave 11:30am for lunch",
        bestSeason: "Year-round",
        proTip: "Try the carapeva fish—unique to this lagoon. Walk 15 minutes from Point 16 to visit the Cachoeira da Costa waterfall.",
        access: "Boat only (40-50 min, R$25 round trip) OR 3-hour trail",
        tags: ["gastronomy", "boat", "waterfall", "unique"],
        personality: "Culinary Explorer",
        vibe: "hidden", effort: "walk", priority: "restaurants", practical: "surprise"
    },

    // EAST COAST - SURF
    {
        name: "Praia da Joaquina",
        nickname: "Joaca",
        emoji: "🏄",
        type: "Championship Surf",
        region: "East",
        description: "Brazil's first international surf competition site (1986). Powerful beach breaks produce waves to 3+ meters. Famous left-handers break from the rocks toward the middle. The adjacent dunes offer sandboarding rentals.",
        waves: 5, crowds: 5, infrastructure: 4,
        water: "Rough surf, steep drop-off, dangerous currents",
        bestFor: "Experienced surfers, sandboard enthusiasts",
        notIdealFor: "Small children, non-swimmers",
        parking: "Paid parking at entrance",
        food: "Kiosks at beach; Lagoa da Conceição 3km away",
        bestTime: "Early morning (less crowd, cleaner conditions)",
        bestSeason: "Winter/autumn for biggest swells",
        proTip: "Works best with South and East swells, offshore winds from northwest. Don't miss the dunes for sandboarding!",
        access: "Drive right up",
        tags: ["surf", "championship", "dunes", "sandboarding"],
        personality: "Wave Hunter",
        vibe: "surf", effort: "drive", priority: "waves", practical: "parking"
    },
    {
        name: "Praia Mole",
        nickname: "The Scene Beach",
        emoji: "🎭",
        type: "Surf & Social Hub",
        region: "East",
        description: "Strong, consistent waves to 3+ meters meet the island's vibrant social scene. The north end is the recognized LGBT+-friendly area, home to Bar do Deca (39+ years operating). Site of Gabriel Medina's first professional victory (2009).",
        waves: 5, crowds: 5, infrastructure: 4,
        water: "Rough surf, steep beach, dangerous currents",
        bestFor: "Surfers, young partygoers, LGBT+ travelers",
        notIdealFor: "Children, non-swimmers (one of most dangerous for drowning)",
        parking: "Paid and free options",
        food: "Bar do Deca, açaí, seafood",
        bestTime: "Morning for surf; afternoon for scene; sunset for parties",
        bestSeason: "Year-round; autumn-winter for biggest waves",
        proTip: "The Gravatá Point at the south corner holds big waves (12+ feet) during major south swells—expert surfers only.",
        access: "Drive right up",
        tags: ["surf", "LGBT+", "nightlife", "social", "scene"],
        personality: "Scene Surfer",
        vibe: "party", effort: "drive", priority: "waves", practical: "infrastructure"
    },
    {
        name: "Praia da Galheta",
        nickname: "Naturist Beach",
        emoji: "🌿",
        type: "Free Spirit's Shore",
        region: "East",
        description: "A conservation area with clothing-optional status, attracting free spirits and nature lovers. Smaller than Mole but with excellent tubular waves. Protected from north/northeast winds at the left corner. Part of the Federação Brasileira de Naturismo.",
        waves: 4, crowds: 2.5, infrastructure: 1.5,
        water: "Moderate surf, great tubes",
        bestFor: "Naturists, LGBT+ travelers, surfers seeking uncrowded waves",
        notIdealFor: "Families, those uncomfortable with nudity",
        parking: "None — park at Praia Mole",
        food: "Limited beach kiosks; bring your own",
        bestTime: "Morning for surf; all day for naturism",
        bestSeason: "Aug-Nov for best surf (east swells = long lefts)",
        proTip: "Naturism status is legally contested—practice at your own discretion. Some harassment incidents reported—stay aware.",
        access: "10-20 min trail from Praia Mole",
        tags: ["naturist", "LGBT+", "surf", "nature", "freedom"],
        personality: "Free Spirit Explorer",
        vibe: "hidden", effort: "walk", priority: "nature", practical: "surprise"
    },
    {
        name: "Barra da Lagoa",
        nickname: "Barra",
        emoji: "🎓",
        type: "Beginner's Paradise",
        region: "East",
        description: "Mellow waves perfect for learning to surf, with a full village of surf schools, hostels, and the Projeto Tamar sea turtle conservation center. The canal walk to the lighthouse is beautiful. Strong localism when conditions are good.",
        waves: 2.5, crowds: 3.5, infrastructure: 5,
        water: "Gentle to moderate, more forgiving",
        bestFor: "Beginners, longboarders, families, backpackers",
        notIdealFor: "Advanced surfers (except rare big days)",
        parking: "Street parking; difficult high season",
        food: "Excellent — traditional seafood, cafes",
        bestTime: "Morning before wind",
        bestSeason: "Autumn/winter for consistency; year-round for beginners",
        proTip: "Visit Projeto Tamar (R$20) for sea turtle conservation. Stay at Sea Wolf Surf Hostel for authentic experience.",
        access: "Drive right up",
        tags: ["beginner", "surf school", "family", "turtles", "village"],
        personality: "Surf Apprentice",
        vibe: "surf", effort: "drive", priority: "waves", practical: "infrastructure"
    },
    {
        name: "Praia do Moçambique",
        nickname: "Moçamba",
        emoji: "🦅",
        type: "Wild & Empty",
        region: "East",
        description: "The least crowded major surf beach with 8.5km of zero facilities. Powerful, tubular waves with heavy shorebreak. Named after the white clam (moçambique/marisco branco) abundant here. Multiple peaks spread along the beach.",
        waves: 5, crowds: 1.5, infrastructure: 1,
        water: "Rough surf, cold, strong currents",
        bestFor: "Experienced surfers, nature lovers, campers",
        notIdealFor: "Families, beginners, anyone needing facilities",
        parking: "Limited; Rio Vermelho Park access",
        food: "None — bring everything",
        bestTime: "Morning with offshore winds",
        bestSeason: "Winter/autumn for biggest swells",
        proTip: "The Trilha Moçambique-Santinho crossing Morro das Aranhas is spectacular for hiking. Camping available at Rio Vermelho Park.",
        access: "Moderate to difficult; 4x4 recommended for some areas",
        tags: ["wild", "empty", "powerful surf", "nature", "camping"],
        personality: "Wilderness Surfer",
        vibe: "surf", effort: "walk", priority: "waves", practical: "surprise"
    },

    // SOUTH COAST
    {
        name: "Praia do Campeche",
        nickname: "The Local Favorite",
        emoji: "🐋",
        type: "Surf & Whale Watching",
        region: "South",
        description: "One of the longest right-hand waves in Brazil when conditions align. The dunes area is protected Natural Heritage. Baleias-franca (right whales) visit July-August as nursery grounds—one of the best watching spots on the island.",
        waves: 4, crowds: 4, infrastructure: 4,
        water: "Rough surf, cold",
        bestFor: "Surfers, kitesurfers, active people",
        notIdealFor: "Non-swimmers, those seeking calm waters",
        parking: "Street and paid lots",
        food: "Excellent — Av. Pequeno Príncipe restaurants",
        bestTime: "Morning for calmer winds",
        bestSeason: "July-August for whale watching",
        proTip: "Best waves with south swell + west/north wind. Watch for whales from shore during winter months!",
        access: "Drive right up",
        tags: ["surf", "whales", "local favorite", "long waves"],
        personality: "Wave Hunter",
        vibe: "surf", effort: "drive", priority: "waves", practical: "parking"
    },
    {
        name: "Praia do Novo Campeche",
        nickname: "The Trendy Hidden Gem",
        emoji: "☕",
        type: "Sophisticated Surf Village",
        region: "South",
        description: "A modern 'mini-bairro' with wide streets, excellent restaurants, organic markets—feels like a surf village. Preserved restinga vegetation gives rustic charm. Low-profile atmosphere attracts digital nomads and quality-of-life seekers.",
        waves: 3.5, crowds: 2.5, infrastructure: 2,
        water: "Rough surf, cold",
        bestFor: "Sophisticated travelers, surfers, families wanting quiet",
        notIdealFor: "Those wanting beach kiosks, nightlife",
        parking: "Good — organized neighborhood",
        food: "Excellent neighborhood restaurants, food trucks",
        bestTime: "Morning for surf, sunset for walks",
        bestSeason: "Year-round; best waves winter/autumn",
        proTip: "Lagoa Pequena nearby offers hidden swimming trails. Check out the organic markets and artisan food trucks.",
        access: "Drive right up",
        tags: ["trendy", "digital nomads", "quiet", "quality", "organic"],
        personality: "Quality Seeker",
        vibe: "relaxation", effort: "drive", priority: "nature", practical: "parking"
    },
    {
        name: "Praia da Armação",
        nickname: "The Gateway",
        emoji: "⛪",
        type: "Historic Base Camp",
        region: "South",
        description: "Main departure point for boats to Ilha do Campeche (the 'Brazilian Caribbean'). Historic 1772 Santa Ana church built during whaling era. Gateway to Matadeiro and Lagoinha do Leste trails. Walk to Ilha das Campanhas for beautiful views.",
        waves: 3, crowds: 3, infrastructure: 4,
        water: "Mixed — calm bay (south), moderate surf (north)",
        bestFor: "Families, history lovers, base for south exploration",
        notIdealFor: "Those seeking isolated beaches",
        parking: "Free street and paid lots",
        food: "Traditional seafood restaurants",
        bestTime: "All day",
        bestSeason: "Year-round; winter for whale watching",
        proTip: "Book boat trips to Ilha do Campeche early in summer. The church and Ilha das Campanhas are worth visiting.",
        access: "Drive right up",
        tags: ["historic", "gateway", "island trips", "family", "versatile"],
        personality: "Explorer Base Camper",
        vibe: "family", effort: "drive", priority: "restaurants", practical: "infrastructure"
    },
    {
        name: "Praia do Matadeiro",
        nickname: "Slaughterhouse Beach",
        emoji: "🌊",
        type: "Surfer's Refuge",
        region: "South",
        description: "Only south island surf option when south winds blow (protected position). Cross the river from Armação early morning when tide is lowest. 900 meters of preserved beach with native vegetation. Starting point for the long trail to Lagoinha do Leste.",
        waves: 4, crowds: 2, infrastructure: 2,
        water: "Rough, crystal clear, cold",
        bestFor: "Surfers, nature lovers, couples",
        notIdealFor: "Families with small children, mobility issues",
        parking: "None — park in Armação",
        food: "One bar; bring snacks",
        bestTime: "Morning for surf",
        bestSeason: "Best with east swell, south winds",
        proTip: "Cross the river early morning at low tide. This is the gateway to the epic Lagoinha do Leste trail (2-3 hours).",
        access: "10-20 min walk — cross river from Armação",
        tags: ["surf", "protected", "nature", "trail gateway"],
        personality: "Trail Surfer",
        vibe: "surf", effort: "walk", priority: "waves", practical: "surprise"
    },
    {
        name: "Pântano do Sul",
        nickname: "Aldeia dos Pescadores",
        emoji: "🦐",
        type: "Seafood Paradise",
        region: "South",
        description: "Largest artisanal fishing center on the island. Bar do Arante is iconic—walls covered with notes from visitors, fresh fish never frozen. Archaeological site with sambaqui (shell mounds) from 4,500 years ago. Boat departures for Lagoinha do Leste.",
        waves: 2, crowds: 3, infrastructure: 4,
        water: "Calm bay, can have undertow in SW section",
        bestFor: "Families, foodies, authentic fishing culture",
        notIdealFor: "Surfers, nightlife seekers",
        parking: "Limited — arrive early; paid available",
        food: "EXCELLENT — legendary Bar do Arante",
        bestTime: "Lunch for seafood",
        bestSeason: "May-July for tainha fishing season",
        proTip: "Must try: sequência de camarão, tainha grelhada, caldeirada at Bar do Arante. Book boat to Lagoinha do Leste here.",
        access: "Drive right up",
        tags: ["seafood", "fishing village", "authentic", "family", "gastronomy"],
        personality: "Culinary Explorer",
        vibe: "family", effort: "drive", priority: "restaurants", practical: "infrastructure"
    },
    {
        name: "Ribeirão da Ilha",
        nickname: "Oyster Capital",
        emoji: "🦪",
        type: "Gastronomic Heritage",
        region: "South",
        description: "Brazil's largest oyster producer with 18th-century Azorean architecture perfectly preserved. Igreja Nossa Senhora da Lapa (1806) built with whale oil and stone. Visit oyster farms for unique experience. Famous sunset views over the bay.",
        waves: 1, crowds: 2, infrastructure: 3,
        water: "Calm, shallow bay",
        bestFor: "Foodies, history lovers, sunset watching",
        notIdealFor: "Beach swimmers (muddy bottom, narrow sand)",
        parking: "Available along road",
        food: "EXCEPTIONAL — Ostradamus, Rancho Açoriano, Porto do Contrato",
        bestTime: "Sunset (west-facing), lunch for oysters",
        bestSeason: "October for Oyster Festival",
        proTip: "Try fresh oysters at the source! Visit the oyster farms and combine with a trip to Naufragados beach.",
        access: "Drive right up",
        tags: ["oysters", "gastronomy", "historic", "sunset", "Azorean"],
        personality: "Gastronomy Connoisseur",
        vibe: "relaxation", effort: "drive", priority: "restaurants", practical: "infrastructure"
    },

    // NORTH COAST
    {
        name: "Jurerê Internacional",
        nickname: "Miami Brasileira",
        emoji: "🥂",
        type: "Luxury Beach Club",
        region: "North",
        description: "Recognized as 'Best Urban Beach in Ibero-America' (2025). Beach clubs with loungers and full service. Calm, warm, emerald-green waters. The New York Times called it 'the place to be' in 2009. Peak scene during New Year's and Carnival.",
        waves: 1, crowds: 5, infrastructure: 5,
        water: "Calm, warm, emerald-green",
        bestFor: "Luxury travelers, party-goers, celebrities",
        notIdealFor: "Budget travelers, those avoiding crowds",
        parking: "Paid at beach clubs and shopping",
        food: "High-end restaurants, Café de la Musique, Parador 12",
        bestTime: "All day; sunset for drinks; night for parties",
        bestSeason: "Summer; New Year's Eve and Carnival especially",
        proTip: "Beach clubs charge entrance but include loungers and full service. Book ahead for major holiday weekends.",
        access: "Drive right up",
        tags: ["luxury", "party", "beach clubs", "celebrities", "nightlife"],
        personality: "Beach Scene Star",
        vibe: "party", effort: "drive", priority: "restaurants", practical: "infrastructure"
    },
    {
        name: "Jurerê Tradicional",
        nickname: "Jurerê Velha",
        emoji: "🏖️",
        type: "Local's Alternative",
        region: "North",
        description: "Same gorgeous calm, warm, crystal-clear water as Internacional but at a fraction of the price. Walk through the alamedas (public paths) designed by Oscar Niemeyer. More affordable with authentic local culture.",
        waves: 1, crowds: 3, infrastructure: 4,
        water: "Calm, warm, crystal-clear green",
        bestFor: "Families, budget travelers, local culture",
        notIdealFor: "Surfers, party-seekers",
        parking: "Moderate — alameda parking",
        food: "Local seafood spots",
        bestTime: "All day; beautiful sunset",
        bestSeason: "Year-round; summer peak",
        proTip: "Walk through Oscar Niemeyer's alamedas design. Same beach quality as Internacional without the premium prices.",
        access: "Drive right up",
        tags: ["family", "budget-friendly", "calm", "local", "Niemeyer"],
        personality: "Smart Beach Lover",
        vibe: "family", effort: "drive", priority: "calm", practical: "parking"
    },
    {
        name: "Praia Brava",
        nickname: "Fierce Beach",
        emoji: "💪",
        type: "North's Surf Spot",
        region: "North",
        description: "One of the best surf spots in the north with powerful waves to 2.5m. Stop at the Mirante da Praia Brava for spectacular photos before descending. Irregular sandy bottom creates powerful breaks. Not for beginners.",
        waves: 4.5, crowds: 4, infrastructure: 4,
        water: "Rough surf, strong currents, to 2.5m",
        bestFor: "Surfers, bodyboarders, young adults",
        notIdealFor: "Young children, non-swimmers",
        parking: "Free lots — arrive before 9am in summer",
        food: "Beach bars, upscale restaurants",
        bestTime: "Morning for surf; sunset from mirante",
        bestSeason: "Year-round; east/southeast swells with west winds",
        proTip: "The mirante (lookout) photo op is mandatory! Dangerous rip currents—respect the ocean here.",
        access: "Drive right up",
        tags: ["surf", "powerful", "mirante", "north surf"],
        personality: "Power Wave Rider",
        vibe: "surf", effort: "drive", priority: "waves", practical: "parking"
    },
    {
        name: "Praia do Santinho",
        nickname: "Archaeology Beach",
        emoji: "🏛️",
        type: "Surf & History",
        region: "North",
        description: "Best surf waves in north region combined with the largest open-air archaeological site on the island. Rock art (Inscrições Rupestres) at Costão do Santinho dates back 4,000-5,000 years. Hosted WQS surf competitions.",
        waves: 4, crowds: 3, infrastructure: 3.5,
        water: "Strong waves, dangerous in rough conditions",
        bestFor: "Surfers, archaeology enthusiasts, hikers",
        notIdealFor: "Families with small children in water",
        parking: "Available near beach and resort",
        food: "Resort dining, kiosks",
        bestTime: "Morning for surf; afternoon for rock art",
        bestSeason: "Year-round",
        proTip: "Don't miss the Inscrições Rupestres (rock art). Trilha do Morro das Aranhas connects to Moçambique with spectacular views.",
        access: "Drive right up",
        tags: ["surf", "archaeology", "rock art", "history", "hiking"],
        personality: "Culture Surfer",
        vibe: "surf", effort: "drive", priority: "waves", practical: "parking"
    },
    {
        name: "Lagoinha do Norte",
        nickname: "Peaceful Escape",
        emoji: "🧘",
        type: "Tranquil Haven",
        region: "North",
        description: "Quiet even in summer, this calm estuary where river meets sea offers perfect conditions for families seeking tranquility and stress recovery. The Trilha do Morro do Rapa starts here—connecting to Praia Brava with stunning views.",
        waves: 1, crowds: 1.5, infrastructure: 2,
        water: "Calm, warm, river-meets-sea",
        bestFor: "Families seeking tranquility, stress recovery",
        notIdealFor: "Nightlife, shopping",
        parking: "Limited — arrive early weekends",
        food: "Simple local restaurants",
        bestTime: "All day; quiet mornings",
        bestSeason: "Year-round; excellent off-season",
        proTip: "The Trilha do Morro do Rapa to Praia Brava (2.8km, 1.5hrs) offers stunning panoramic views.",
        access: "Drive right up",
        tags: ["peaceful", "family", "calm", "estuary", "hiking"],
        personality: "Tranquility Seeker",
        vibe: "relaxation", effort: "drive", priority: "calm", practical: "surprise"
    },
    {
        name: "Praia do Forte",
        nickname: "Hidden Northern Gem",
        emoji: "🏰",
        type: "Historic Hideaway",
        region: "North",
        description: "Very quiet with historic Fortaleza de São José da Ponta Grossa (built 1739-1745). Watch local oyster farming boats—this is where famous Floripa oysters originate. Perfect for history buffs seeking solitude.",
        waves: 1, crowds: 1.5, infrastructure: 2,
        water: "Calm, warm",
        bestFor: "History buffs, solitude seekers",
        notIdealFor: "Those wanting amenities",
        parking: "Limited — arrive early summer",
        food: "Few seafood restaurants",
        bestTime: "Morning; combine with fort visit",
        bestSeason: "Year-round",
        proTip: "Visit Fortaleza de São José da Ponta Grossa (R$8 entry). The oyster farming boats are fascinating to watch.",
        access: "Drive right up",
        tags: ["historic", "fort", "quiet", "oysters", "solitude"],
        personality: "History Explorer",
        vibe: "hidden", effort: "drive", priority: "nature", practical: "surprise"
    },

    // LAGOON & CALM WATERS
    {
        name: "Lagoa da Conceição",
        nickname: "Avenida das Rendeiras",
        emoji: "🚣",
        type: "Water Sports Hub",
        region: "Lagoon",
        description: "Brackish lagoon reaching 27°C in summer, perfect for SUP and kayak. Excellent restaurants line the shore. Rent SUP at EasySUP (R$30/half hour). Best route: downwind across lagoon to Costa da Lagoa restaurants.",
        waves: 1, crowds: 3, infrastructure: 4,
        water: "Brackish lagoon, warm (27°C summer)",
        bestFor: "Families, SUP, kayak, couples dining",
        notIdealFor: "Surfers, those expecting beach sand",
        parking: "Difficult summer; paid lots R$6/hour",
        food: "Excellent — Canto do Chico, many seafood spots",
        bestTime: "Late afternoon for sunset",
        bestSeason: "Year-round",
        proTip: "Check balneability reports before swimming. Best SUP route: paddle to Costa da Lagoa for lunch!",
        access: "Drive right up",
        tags: ["SUP", "kayak", "dining", "sunset", "water sports"],
        personality: "Paddle Explorer",
        vibe: "relaxation", effort: "drive", priority: "calm", practical: "infrastructure"
    },
    {
        name: "Lagoa do Peri",
        nickname: "Freshwater Heaven",
        emoji: "💧",
        type: "Blue Flag Paradise",
        region: "South",
        description: "The largest freshwater lake on the Santa Catarina coast, Blue Flag certified as among Brazil's cleanest swimming areas. Best SUP/kayak spot for beginners. Take Trilha da Gurita to beautiful Cachoeira da Gurita waterfall.",
        waves: 1, crowds: 2, infrastructure: 2,
        water: "FRESHWATER — Blue Flag certified",
        bestFor: "Families with children, picnics, kayak",
        notIdealFor: "Ocean lovers",
        parking: "FREE large lot",
        food: "Peri Restaurante; bring picnic",
        bestTime: "Morning for birds; all day",
        bestSeason: "Year-round",
        proTip: "Visit Projeto Lontra (Otter Project)—book ahead at (48) 3237-5071. The Trilha da Gurita waterfall is beautiful.",
        access: "Drive right up",
        tags: ["freshwater", "family", "Blue Flag", "clean", "kayak"],
        personality: "Nature Family",
        vibe: "family", effort: "drive", priority: "calm", practical: "parking"
    },
    {
        name: "Santo Antônio de Lisboa",
        nickname: "Sunset Capital",
        emoji: "🌅",
        type: "Golden Hour Destination",
        region: "North Bay",
        description: "Famous sunsets over the bay with the 'Rota Gastronômica do Sol Poente' (Setting Sun Gastronomic Route). Visit Feira das Alfaias artisan fair on weekends. Igreja Nossa Senhora das Necessidades (1750) and the 1860 functioning flour mill.",
        waves: 1, crowds: 2, infrastructure: 4,
        water: "Calm bay (not ideal for swimming)",
        bestFor: "Sunset watching, gastronomy, couples",
        notIdealFor: "Beach swimming",
        parking: "Street and restaurant lots",
        food: "EXCEPTIONAL — Rota Gastronômica do Sol Poente",
        bestTime: "4-7pm — FAMOUS sunsets",
        bestSeason: "Year-round",
        proTip: "Visit Casarão Engenho dos Andrade (1860 functioning flour mill)—call (48) 9615-4080 for reservation.",
        access: "Drive right up",
        tags: ["sunset", "gastronomy", "romantic", "historic", "Azorean"],
        personality: "Sunset Chaser",
        vibe: "relaxation", effort: "drive", priority: "sunset", practical: "infrastructure"
    },
    {
        name: "Sambaqui",
        nickname: "The Authentic Village",
        emoji: "🎸",
        type: "Local Music Scene",
        region: "North Bay",
        description: "Sunday nights, locals gather for live Brazilian roots music at a fisherman's house on the beach—tourists rarely find this. Multiple beach sections to explore. Archaeological significance from prehistoric shell mounds (sambaqui).",
        waves: 1, crowds: 2, infrastructure: 3,
        water: "Calm bay",
        bestFor: "Families, sunset, authentic experience",
        notIdealFor: "Pristine sand beach seekers",
        parking: "Free along road",
        food: "Botequim das Flores (2023 champion), Posto Alfandegário",
        bestTime: "Late afternoon; Sunday for live music",
        bestSeason: "Year-round",
        proTip: "Sunday nights: find the fisherman's house with live Brazilian roots music. Locals only—magical experience.",
        access: "Drive right up",
        tags: ["authentic", "music", "local", "sunset", "archaeology"],
        personality: "Culture Seeker",
        vibe: "relaxation", effort: "drive", priority: "sunset", practical: "surprise"
    }
];

// Quiz questions for beach finder
const beachQuestions = [
    {
        label: "The Call",
        text: "What's calling you to the shore?",
        options: [
            { value: "surf", icon: "🏄", title: "Waves & Adventure", desc: "I came to ride" },
            { value: "relaxation", icon: "🧘", title: "Peace & Restoration", desc: "Reset my soul" },
            { value: "family", icon: "👨‍👩‍👧", title: "Family Time", desc: "Making memories together" },
            { value: "hidden", icon: "🗺️", title: "Secret Places", desc: "Off the beaten path" },
            { value: "party", icon: "🎉", title: "Social Scene", desc: "Where the people are" }
        ]
    },
    {
        label: "The Journey",
        text: "How much effort to reach paradise?",
        options: [
            { value: "drive", icon: "🚗", title: "Drive Right Up", desc: "Beach should be easy" },
            { value: "walk", icon: "🚶", title: "Short Walk", desc: "A little effort, big reward" },
            { value: "hike", icon: "🥾", title: "Trail Adventure", desc: "The journey IS the destination" }
        ]
    },
    {
        label: "The Dream",
        text: "What matters most when you arrive?",
        options: [
            { value: "waves", icon: "🌊", title: "Epic Waves", desc: "Surfable swells" },
            { value: "calm", icon: "🪷", title: "Calm Waters", desc: "Peaceful swimming" },
            { value: "restaurants", icon: "🍽️", title: "Food & Drinks", desc: "Beachside bites" },
            { value: "nature", icon: "🌴", title: "Pristine Nature", desc: "Untouched beauty" },
            { value: "sunset", icon: "🌅", title: "Sunset Views", desc: "Golden hour magic" }
        ]
    },
    {
        label: "The Reality",
        text: "One more thing that would make it perfect?",
        options: [
            { value: "infrastructure", icon: "🏪", title: "Good Amenities", desc: "Restrooms, showers, rentals" },
            { value: "parking", icon: "🅿️", title: "Easy Parking", desc: "No stress arrival" },
            { value: "dog", icon: "🐕", title: "Dog-Friendly", desc: "Bringing my buddy" },
            { value: "surprise", icon: "🎲", title: "Surprise Me", desc: "I'm feeling adventurous" }
        ]
    }
];

// Helper function to calculate best beach match
function calculateBeachMatch(answers) {
    let bestMatch = beaches[0];
    let bestScore = 0;

    beaches.forEach(beach => {
        let score = 0;
        if (beach.vibe === answers.vibe) score += 5;
        if (beach.effort === answers.effort) score += 3;
        if (beach.priority === answers.priority) score += 4;
        if (beach.practical === answers.practical) score += 2;

        // Tag bonuses
        Object.values(answers).forEach(answer => {
            if (beach.tags.some(tag => tag.toLowerCase().includes(answer.toLowerCase()))) {
                score += 1;
            }
        });

        // Special matching logic
        if (answers.priority === 'calm' && beach.waves <= 2) score += 2;
        if (answers.priority === 'waves' && beach.waves >= 4) score += 2;
        if (answers.practical === 'infrastructure' && beach.infrastructure >= 4) score += 2;

        if (score > bestScore) {
            bestScore = score;
            bestMatch = beach;
        }
    });

    return bestMatch;
}
